# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
  
    runs-on: ubuntu-latest
  
    steps:
  
    - name: Setup Ruby environment with ruby-build
  # You may pin to the exact commit or the version.
      uses: ruby/setup-ruby@f20f1eae726df008313d2e0d78c5e602562a1bcf
      with:
        ruby-version: 2.6.5

  test:
  
    runs-on: ubuntu-latest
  
    - name: Test Ruby project
      run: echo "Run required project tests in this step"        
    
  scan:

    runs-on: ubuntu-latest
      
    steps:
    
    
    - uses: actions/checkout@v2
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: https://jbernienexusiq.eu.ngrok.io
        
        #use variables 
        username: admin
        password: admin1234
        applicationId: device-security
        stage: Build
        target: ./Gemfile.lock
    
 
